spring.application.name=operations-ai-agent

server.port=8082

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen2.5:7b

# MCP Server
spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.name=operations-ai-agent
spring.ai.mcp.client.version=1.0.0
spring.ai.mcp.client.type=SYNC

spring.ai.mcp.client.streamable-http.connections.operations-mcp.url=http://localhost:8090
spring.ai.mcp.client.streamable-http.connections.operations-mcp.endpoint=/mcp

